### ISSUE TITLE
Написание статьи о "Лайтнинг-кошельках"

### ISSUE THREAD

**Issue by bitcoin21ideas** [21ideas-org/21ideas.org#100]
Баунти за **написание** статьи-сравнения актуальных Лайтнинг-кошелькхов для раздела "Практика -> Лайтнинг" = 5000 сат

В качестве примера можно взять уже устаревшую статью здесь: https://www.21ideas.org/theory-ln-lightning-wallets/

> Не забудьте ознакомиться с гидами по добавлению статей (ссылки доступны во второй колонке раздела "[Принять участие](https://new.21ideas.org/contribute/)" - "Статьи"), прежде чем браться за задание.

### ! Если вы решили взяться за задание, оставьте комментарий под этим issue, чтобы потом не оказалось, что над ним работает несколько человек

> Баунти оплачиваются через сеть Лайтнинг. Для получения вознаграждения укажите свой [лайтнинг-адрес](https://new.21ideas.org/lajtning-adresa/) в комментарии к PR.

**Comment by TouchstoneTheGreat** [comment]
https://new.21ideas.org/ https://new.21ideas.org/lajtning-adresa/ https://new.21ideas.org/contribute/
404 не найдено

**Comment by TouchstoneTheGreat** [comment]
куда мне нужно отправить руководство/блог/статьи?

**Comment by bitcoin21ideas** [comment]
В этом гиде описана процедура добавления статей: https://21ideas.org/github/

**Comment by bitcoin21ideas** [comment]
Я взялся за этот гид
