### ISSUE TITLE
Подготовить гид по кошельку Самурай

### ISSUE THREAD

**Issue by bitcoin21ideas** [21ideas-org/21ideas.org#102]
Баунти за **написание** гида по кошельку Samourai "Практика -> Взаимодействие" = 21,000 сат

> Не забудьте ознакомиться с гидами по добавлению статей (ссылки доступны во второй колонке раздела "[Принять участие](https://new.21ideas.org/contribute/)" - "Статьи"), прежде чем браться за задание.

### ! Если вы решили взяться за задание, оставьте комментарий под этим issue, чтобы потом не оказалось, что над ним работает несколько человек

> Баунти оплачиваются через сеть Лайтнинг. Для получения вознаграждения укажите свой [лайтнинг-адрес](https://new.21ideas.org/lajtning-adresa/) в комментарии к PR.

**Comment by btclinux** [comment]
Возьмусь, но быстро не обещаю, очень много информации нужно передать

**Comment by bitcoin21ideas** [comment]
Да, конечно. Указываю, чтобы показать желаемое направление развития проекта. Мне кажется нужно больше гидов и материалов касаемо приватности. Такая статья убьет двух зайцев. Спешки нет!

**Comment by btclinux** [comment]
На самом деле, одной вряд ли обойдётся. Ну, посмотрим
