### ISSUE TITLE
Оформление раздела Книги

### ISSUE THREAD

**Issue by bitcoin21ideas** [21ideas-org/21ideas.org#140]
Баунти за разработку и имплементацию оформления раздела "Книги". Кастомный CSS, дизайн странички в разделе "Кроличья нора" для отображения книг в разделе более дружелюбным и наглядным для посетителя образом.

В качестве примера можно рассмотреть оформление Библиотеки Биткоинера от @heyalmoo  в [Notion](https://bitcoin-citadel.notion.site/5326bf9ba0f84f81bf4b2d6e0035f9f3?v=0132c1bf02784d7491ee96c60a2050df).

**Баунти - 21000 сат**

**Comment by Ayush-Vish** [comment]
@bitcoin21ideas  Я хочу поработать над этой задачей. Пожалуйста, назначьте её мне.
