### ISSUE TITLE
Добавление альтернативных ссылок на статьи

### ISSUE THREAD

**Issue by bitcoin21ideas** [21ideas-org/21ideas.org#141]
Баунти за добавление альтернативных ссылок на все статьи, перенесенные с текущего сайта. Это необходимо для того, чтобы старые ссылки, уже висящие на многих сайтах, тг каналах и других источниках, не поломались при переезде. 

Подробности оформления - в [этом пуля-реквесте](https://github.com/21ideas-org/21ideas.org/pull/128).

**Баунти 42,000 сат**

**Comment by btclinux** [comment]
Беру
