### ISSUE TITLE
Добавить серию статей "Постепенно, затем внезапно"

### ISSUE THREAD

**Issue by bitcoin21ideas** [21ideas-org/21ideas.org#25]
Баунти за перенос статей из серии "Постепенно, затем внезапно" = 21,000 сатоши.

Статьи доступны по [этой ссылке](https://www.21ideas.org/tag/gradually-then-suddenly/). 

Важные пункты:  

- Статьи необходимо добавлять в оригинальном порядке. Порядок появления статей можно отследить в блоге "Unchained Capital". Первые две статьи уже залиты на сайт, следующая статья к добавлению - "Биткоин не слишком волатилен". Эта и последующие статьи доступны на [страничке 13 блога Unchained](https://unchained.com/blog/?_blog_categories=all&_paged=13). Дальше - по порядку (от более старых к новым).
- Не забудьте указывать дату изначального выпуска статей в голове каждой статьи. Также важно ознакомиться с гидами по добавлению статей (ссылки доступны во второй колонке раздела "[Принять участие](https://new.21ideas.org/contribute/)" - "Статьи"), прежде чем браться за задание.

> Дополнительные 21,000 сат будут начислены за перевод последнего эссе Паркера Льюиса "[Биткоин - это не хедж](https://unchained.com/blog/bitcoin-is-not-a-hedge/)".

### ! Если вы решили взяться за задание, оставьте комментарий под этим issue, чтобы потом не оказалось, что над ним работает несколько человек

> Баунти оплачиваются через сеть Лайтнинг. Для получения вознаграждения укажите свой [лайтнинг-адрес](https://new.21ideas.org/lajtning-adresa/) в комментарии к PR.

**Comment by Radiokot** [comment]
Будет указываться дата первоначального выхода оригинала.

**Comment by Radiokot** [comment]
Еще занимаюсь, пока добавил 8 статей.
