### ISSUE TITLE
Добавить серию статей "Генезис-файлы"

### ISSUE THREAD

**Issue by bitcoin21ideas** [21ideas-org/21ideas.org#27]
Баунти за перенос статей из серии "Генезис-файлы" = 10,000 сат.

Статьи доступны по [этой ссылке](https://www.21ideas.org/tag/genesis-files/).

Важные пункты:

- Статьи необходимо добавлять в оригинальном порядке. 
- Не забудьте указывать дату выпуска оригинальных статей в голове каждой статьи. Также важно ознакомиться с гидами по добавлению статей (ссылки доступны во второй колонке раздела "[Принять участие](https://new.21ideas.org/contribute/)" - "Статьи"), прежде чем браться за задание.

### ! Если вы решили взяться за задание, оставьте комментарий под этим issue, чтобы потом не оказалось, что над ним работает несколько человек

> Баунти оплачиваются через сеть Лайтнинг. Для получения вознаграждения укажите свой [лайтнинг-адрес](https://new.21ideas.org/lajtning-adresa/) в комментарии к PR.

**Comment by btclinux** [comment]
Беру
