### ISSUE TITLE
Суверенитет посредством математики

### ISSUE THREAD

**Issue by bitcoin21ideas** [21ideas-org/21ideas.org#3]
Объявляю первое баунти за добавление книги "Суверенитет посредством математики" в соответствующий раздел сайта "кроличья нора": https://github.com/21ideas-org/21ideas.org/tree/main/content.ru/docs/Rabbithole/Books/Suverenitet-posredstvom-matematiki

! Вознаграждение составляет 21,000 сат.

**Comment by Radiokot** [comment]
I'm on it

**Comment by bitcoin21ideas** [comment]
Done, thanks! Sats sent ⚡️
