### ISSUE TITLE
Добавить курс "Биткоин от А до Я"

### ISSUE THREAD

**Issue by bitcoin21ideas** [21ideas-org/21ideas.org#34]
Баунти за добавление курса "Биткоин от А до Я" в раздел "Старт" = 21000 сат. Вознаграждение будет варьироваться в зависимости от доступных на сайте статей и может достичь 100,000 сат.

Курс доступен по ссылке: https://www.21ideas.org/basics-bitcoin-course/

> Не забудьте ознакомиться с гидами по добавлению статей (ссылки доступны во второй колонке раздела "[Принять участие](https://new.21ideas.org/contribute/)" - "Статьи"), прежде чем браться за задание.

### ! Если вы решили взяться за задание, оставьте комментарий под этим issue, чтобы потом не оказалось, что над ним работает несколько человек

> Баунти оплачиваются через сеть Лайтнинг. Для получения вознаграждения укажите свой [лайтнинг-адрес](https://new.21ideas.org/lajtning-adresa/) в комментарии к PR.

**Comment by bitcoin21ideas** [comment]
Если вы хотите взяться за эту работу, начать стоит с добавления на сайт статей, входящих в курс. Оставьте комментарий, чтобы обсудить лучший подход к реализации этого самого объемного проекта в рамках библиотеки.

**Comment by bitcoin21ideas** [comment]
Пока что эта задача отложена до тех пор, пока не на сайте не появятся все входящие в курс материалы. Первый претендент на добавление курса - @btclinux

**Comment by btclinux** [comment]
В процессе
