### ISSUE TITLE
Добавить статью "Все - мошенники"

### ISSUE THREAD

**Issue by bitcoin21ideas** [21ideas-org/21ideas.org#35]
Баунти за добавление статьи "Все - мошенники" в раздел "Теория -> Философия" = 1500 сат

Статья доступна по ссылке: https://www.21ideas.org/theory-philosophy-everyone-is-a-scammer/

> Не забудьте ознакомиться с гидами по добавлению статей (ссылки доступны во второй колонке раздела "[Принять участие](https://new.21ideas.org/contribute/)" - "Статьи"), прежде чем браться за задание.

### ! Если вы решили взяться за задание, оставьте комментарий под этим issue, чтобы потом не оказалось, что над ним работает несколько человек

> Баунти оплачиваются через сеть Лайтнинг. Для получения вознаграждения укажите свой [лайтнинг-адрес](https://new.21ideas.org/lajtning-adresa/) в комментарии к PR.

**Comment by bitcoin21ideas** [comment]
Пока что эта задача отложена до тех пор, пока не на сайте не появятся все входящие в курс материалы. Первый претендент на добавление курса - @btclinux

**Comment by btclinux** [comment]
Беру
