### ISSUE TITLE
Добавить статью "Proof of Stake - это скам"

### ISSUE THREAD

**Issue by bitcoin21ideas** [21ideas-org/21ideas.org#39]
Баунти за добавление статьи "Proof of Stake - это скам" в раздел "Теория -> Протокол" = 1500 сат

Статья доступна по ссылке: https://www.21ideas.org/theory-protocol-pos-is-a-scam/

> Не забудьте ознакомиться с гидами по добавлению статей (ссылки доступны во второй колонке раздела "[Принять участие](https://new.21ideas.org/contribute/)" - "Статьи"), прежде чем браться за задание.

### ! Если вы решили взяться за задание, оставьте комментарий под этим issue, чтобы потом не оказалось, что над ним работает несколько человек

> Баунти оплачиваются через сеть Лайтнинг. Для получения вознаграждения укажите свой [лайтнинг-адрес](https://new.21ideas.org/lajtning-adresa/) в комментарии к PR.

**Comment by btclinux** [comment]
Беру
