### ISSUE TITLE
Добавить статью "Об удобстве взаимодействия с Биткоином"

### ISSUE THREAD

**Issue by bitcoin21ideas** [21ideas-org/21ideas.org#42]
Баунти за добавление статьи "Об удобстве взаимодействия с Биткоином" в раздел "Теория -> Протокол" = 1000 сат

Статья доступна по ссылке: https://www.21ideas.org/theory-protocol-bitcoin-interaction/

> Не забудьте ознакомиться с гидами по добавлению статей (ссылки доступны во второй колонке раздела "[Принять участие](https://new.21ideas.org/contribute/)" - "Статьи"), прежде чем браться за задание.

### ! Если вы решили взяться за задание, оставьте комментарий под этим issue, чтобы потом не оказалось, что над ним работает несколько человек

> Баунти оплачиваются через сеть Лайтнинг. Для получения вознаграждения укажите свой [лайтнинг-адрес](https://new.21ideas.org/lajtning-adresa/) в комментарии к PR.

**Comment by bitcoin21ideas** [comment]
Спасибо за добавление статьи, @vjik . На какой ЛН-адрес / инвойс можно выслать саты?

**Comment by vjik** [comment]
Инвойс: `lnbc1pj3yulepp5787jx6summa4gd92szaz6gzvlxsdvpqycxtmkrvh8qqer83tjlcqdqqxqyjw5q9q7sqqqqqqqqqqqqqqqqqqqqqqqqq9qsqsp5pvtwfsr3vd27tzf8c2n4nmjwt6e2uee5yk2n9fn80j3268tklv3qrzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glcll764ggx38kg9yqqqqlgqqqqqeqqjqryfjp3m990sth6r3wc0wuh39wd4qsrtlgfhgam2pwzjgukzwysmy9dt64xfteamjarmkmuw57fe97gxrld7ych6xe65fya9fnjx9xhqpt2lu7k`

**Comment by bitcoin21ideas** [comment]
он пустой, не могу оплатить. можешь скинуть на 1000 сат сразу инвойс плиз

**Comment by vjik** [comment]
lnbc10u1pj3y7cjpp5vfaq6njs7hqamtcsr7emc7lw5uea292vnn8ztrwh6xwj5lwjmkvqdqqxqyjw5q9q7sqqqqqqqqqqqqqqqqqqqqqqqqq9qsqsp5hn4lzmj8mjpcazdtvnx9y2ghysrd8qxz3gmzlht6vvf4kcx22e4srzjqwryaup9lh50kkranzgcdnn2fgvx390wgj5jd07rwr3vxeje0glcll764ggx38kg9yqqqqlgqqqqqeqqjq0a9ljjwgpn6ulrly0guqhyew5ty6ju5a27ll86zcan338d0p49cyhvff0jc6g3v5n4zerd6r2ewhrecgwewlk6apqm3zqvf6vwsezzgqu6hrl8`

**Comment by bitcoin21ideas** [comment]
отлично, оплачено. ждем новых PR! 😉
