### ISSUE TITLE
Заполнение раздела "Видео"

### ISSUE THREAD

**Issue by bitcoin21ideas** [21ideas-org/21ideas.org#6]
Баунти 50 000 сат

Раздел "Видео" требует заполнения достойными материалами на темы Биткоина, АЭШ и т п. 

Гитхаб, где представлена структура заполнения доступен по ссылке: https://github.com/21ideas-org/21ideas.org/tree/main/content.ru/docs/Rabbithole/Videos

Ссылка на страничку на сайте: https://new.21ideas.org/docs/Rabbithole/Videos/

Задача - залить материалы с каналов https://www.youtube.com/@21ideas и https://www.youtube.com/@BitKorn. Другие стоящие русскоязычные материалы, разумеется, приветствуются. 

Единственное  требование - нужно локально запустить сайт, потому что в этом разделе довольно хитрая структура из-за шорткодов, обеспечивающих выпадающее меню самих видосов. Если локально не запустить и не проверять с каждым новым добавленным видео/элементом, очень высока вероятность, что что-то сломается. 

Предложения по улучшению и фидбэк можно оставить в нашем специально отведенном чате: https://t.me/+er6lvo_nchc3YmQ0

**Comment by Radiokot** [comment]
Working on it

**Comment by bitcoin21ideas** [comment]
Thanks for your effort! Sats sent. Please have a look at the Sailor series - I only added two videos as an example, would appreciate if you could add the rest of them.

![proof-of-payment](https://cdn.nostr.build/p/v7A6.jpg)

---

@mell4ce can you please have a look at lazy load shortcodes please and notify @Radiokot when he can fix them. (even though everything loads just fine for me, people with slow internet connection might struggle)

**Comment by bitcoin21ideas** [comment]
Lazy loading added to the shortcodes for YouTube videos in the "Videos" section. Summoning @mell4ce to have a look and add a corresponding shortcode to enable lazy loading

**Comment by Radiokot** [comment]
Here: https://github.com/21ideas-org/21ideas.org/pull/9

**Comment by bitcoin21ideas** [comment]
oh, so you did it yourself?
